name: NPM Publish
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@dits'
      - run: npm install
      - run: npm run build

      - name: Set Build Number
        id: set-build-num
        run: |
          VERSION=$(echo $GITHUB_REF | cut -d / -f 3)
          echo "Setting NPM version to $VERSION"
          npm version --no-git-tag-version $VERSION
          cat package.json

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.DITS_NPM_PUBLISH_TOKEN}}
